app = "pc-backend"
primary_region = "sin"

[build]
  builder = "python"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  command = "python main.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
