app = "auth-api-nvdempim"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  DATABASE_URL = "postgresql://postgres.emfvgkmuwfguexaowavs:CG0Pz6GCM82syMgc@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres"
  GEMINI_API_KEY = "AIzaSyDBhwyLlC3jO1ek2g0UyK3lp11CO8v1alg"
  SMTP_USER = "welcome@guixian.cn"
  SMTP_PASSWORD = "GuiXian7758"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
