app = "pc-backend"
primary_region = "sin"

[build]
  builder = "python"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  DATABASE_URL = "postgresql://postgres.emfvgkmuwfguexaowavs:CG0Pz6GCM82syMgc@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres"
  SMTP_HOST = "smtpdm.aliyun.com"
  SMTP_PORT = "465"
  SMTP_USER = "welcome@guixian.cn"
  SMTP_PASSWORD = "GuiXian7758"
  GEMINI_API_KEY = "AIzaSyDBhwyLlC3jO1ek2g0UyK3lp11CO8v1alg"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  command = "python main.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
