app = "pc-backend"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"
  PYTHONPATH = "/app"
  PYTHON_VERSION = "3.12"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  command = "python -m pip install -r requirements.txt && python -m uvicorn main:app --host 0.0.0.0 --port 8000"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
